#!/bin/bash
awk '
/document\.addEventListener\("DOMContentLoaded", function\(\) \{/ {
    print $0
    print "      try {"
    print "        var p = new URLSearchParams(window.location.search);"
    print "        var err = p.get(\"error\");"
    print "        if (err) {"
    print "          var f = document.querySelector(\"form\");"
    print "          if (f) {"
    print "            var d = document.createElement(\"div\");"
    print "            d.className = \"form-error-alert\";"
    print "            d.style.cssText = \"background:#fee2e2;color:#991b1b;padding:12px;border-radius:6px;border:1px solid #f87171;margin-bottom:16px;font-weight:500;text-align:center;font-size:14px;\";"
    print "            d.textContent = err;"
    print "            f.insertBefore(d, f.firstChild);"
    print "            if(window.history && window.history.replaceState) {"
    print "              p.delete(\"error\");"
    print "              var newUrl = window.location.pathname + (p.toString() ? \"?\" + p.toString() : \"\") + window.location.hash;"
    print "              window.history.replaceState({}, \"\", newUrl);"
    print "            }"
    print "          }"
    print "        }"
    print "      } catch(e) {}"
    print ""
    print "      // Intercept form submits for seamless validation without reset"
    print "      var forms = document.querySelectorAll(\"form[action='\''/api/lead'\'']\");"
    print "      forms.forEach(function(f) {"
    print "        f.addEventListener(\"submit\", function(e) {"
    print "          e.preventDefault();"
    print "          "
    print "          var existingAlert = f.querySelector(\".form-error-alert\");"
    print "          if (existingAlert) existingAlert.remove();"
    print "          "
    print "          var submitBtn = f.querySelector(\"button[type='\''submit'\'']\") || f.querySelector(\"input[type='\''submit'\'']\");"
    print "          var originalBtnText = submitBtn ? (submitBtn.textContent || submitBtn.value) : \"\";"
    print "          if (submitBtn) {"
    print "            submitBtn.disabled = true;"
    print "            if (submitBtn.tagName === \"BUTTON\") submitBtn.textContent = \"Lütfen Bekleyin...\";"
    print "            else submitBtn.value = \"Lütfen Bekleyin...\";"
    print "          }"
    print ""
    print "          var formData = new FormData(f);"
    print "          var jsonBody = {};"
    print "          formData.forEach(function(value, key) {"
    print "            if (jsonBody[key] !== undefined) {"
    print "              if (!Array.isArray(jsonBody[key])) {"
    print "                jsonBody[key] = [jsonBody[key]];"
    print "              }"
    print "              jsonBody[key].push(value);"
    print "            } else {"
    print "              jsonBody[key] = value;"
    print "            }"
    print "          });"
    print "          "
    print "          fetch(\"/api/lead\", {"
    print "            method: \"POST\","
    print "            headers: { \"Content-Type\": \"application/json\" },"
    print "            body: JSON.stringify(jsonBody)"
    print "          })"
    print "          .then(async function(res) {"
    print "            if (res.ok) {"
    print "              var red = formData.get(\"_redirect\");"
    print "              if (red) window.location.href = red;"
    print "              else alert(\"Talebiniz başarıyla alındı.\");"
    print "            } else {"
    print "              var data = await res.json().catch(function(){ return {}; });"
    print "              var errMsg = data.error || \"Geçersiz bilgi girdiniz. Lütfen kontrol edin.\";"
    print "              "
    print "              var d = document.createElement(\"div\");"
    print "              d.className = \"form-error-alert\";"
    print "              d.style.cssText = \"background:#fee2e2;color:#991b1b;padding:12px;border-radius:6px;border:1px solid #f87171;margin-bottom:16px;font-weight:500;text-align:center;font-size:14px;\";"
    print "              d.textContent = errMsg;"
    print "              f.insertBefore(d, f.firstChild);"
    print "              "
    print "              if (submitBtn) {"
    print "                submitBtn.disabled = false;"
    print "                if (submitBtn.tagName === \"BUTTON\") submitBtn.textContent = originalBtnText;"
    print "                else submitBtn.value = originalBtnText;"
    print "              }"
    print "            }"
    print "          }).catch(function(err) {"
    print "            if (submitBtn) {"
    print "              submitBtn.disabled = false;"
    print "              if (submitBtn.tagName === \"BUTTON\") submitBtn.textContent = originalBtnText;"
    print "              else submitBtn.value = originalBtnText;"
    print "            }"
    print "          });"
    print "        });"
    print "      });"
    
    # We need to skip the original URL search params logic
    # We will set a flag to skip lines until </script>
    skip=1
    next
}
skip && /<\/script>/ {
    skip=0
    print "  </script>"
    next
}
skip { next }
{ print }
' functions/_shared/hub-renderer.js > temp_hub.js
mv temp_hub.js functions/_shared/hub-renderer.js
